### PR TITLE
Update step name to match its action

### PR DESCRIPTION
**Pull request by ipince**

### CODE REVIEW

**Comment by ipince** [comment]
Also did the PR to check the workflow :)

**Comment by ipince** [comment]
Ah, looks like @robrich needs to approve the workflow

**Comment by robrich** [comment]
Good catch!  Merged.

**Comment by robrich** [comment]
Good point. I've seen the workflow run, but never tried it myself. I'm curious to see the approval screen you saw. ... off to test this with a few GitHub accounts. :D

**Pull request merged**
